### ISSUE TITLE
Casefold user names

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-gitter#10]
Now that the legendary SPEC-1 has been resolved, we have some work to do here.

Gitter/github user IDs contain only a subset of the allowed MXID characters so that's fine, but we do need to casefold because capitals, while not significant for uniqueness purposes, are preserved.

It remains a question of design on exactly where these casefolding operations should be performed. Possibly a question for @Kegsay

**Comment by leonerd** [comment]
An initial hack done in e279607
It's probably not the right place to leave that, but it'll do for now until we find a better place in the code.

**Comment by Kegsay** [comment]
We should have a pure functional, er, function in the bridge lib to do our quirky casefold operations. It would be a disaster to expect everyone to implement their own.

**Comment by leonerd** [comment]
That code managed to go missing in the `MatrixIdTemplate` rewrite. Trying to apply it again causes much breakage, because now we have so many existing users that are wrongly-cased, they break quite badly if I just apply this simply. More work will be needed. I'll close this bug in favour of #12
