### ISSUE TITLE
automatically convert between IRC and gitter nicks

### ISSUE THREAD

**Issue by nhooyr** [matrix-org/matrix-appservice-gitter#15]
For example, when someone types `JustinMKeyesGitt: message` on IRC it becomes `@justinmk: message` automatically for gitter and vice versa.

**Comment by leonerd** [comment]
This is highly nontrivial. It requires not one but two levels of translation; one at the Gitter->Matrix and one at Matrix->IRC (or vice versa depending on traffic flow direction). That would mean the intermediate message format of Matrix room messages would need a native understanding of "mention" tagging. Currently this does not exist.

**Comment by strk** [comment]
The Gitter->Matrix translation might benefit of a rethought on itself, to make mentions of gitter nicks work

**Comment by auscompgeek** [comment]
Since matrix-org/matrix-appservice-irc#573 is a thing these days, I think all that needs to be done is pills to Gitter mentions, which I guess is #53.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
