### ISSUE TITLE
Investigate why the bridge stopped

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-gitter#25]
It just stopped. At around 08:22 this morning (2016/Sept/29). Nothing apparent in the log file. We received messages up until that time and then we just didn't any more. I tried poking various places on gitter and none of the messages ever turned up.

**Comment by leonerd** [comment]
Just did it again, around 18:35 today (2016/Oct/04).

What's interesting to note this time (though I believe last time it happened as well) is that all actual messaging stopped working, though presence information remained. We were still receiving "eyeball" events from gitter and forwarding them into matrix as presence notifications, just not textual messages.

I ran `lsof` against the process this time. It listed two connections up to amazonaws, which I expect are the event stream websockets:

```
node    1223 gitteras   11u  IPv4          465712763      0t0       TCP ldc-prd-matrix-003.openmarket.com:51305->ec2-52-0-125-130.compute-1.amazonaws.com:https (ESTABLISHED)
node    1223 gitteras   13u  IPv4          465716563      0t0       TCP ldc-prd-matrix-003.openmarket.com:51314->ec2-52-0-125-130.compute-1.amazonaws.com:https (ESTABLISHED)
```

So I don't think the TCP sockets just died.

**Comment by leonerd** [comment]
Possible progress!

During unrelated (local) testing, I created a new room on gitter to test a feature, then once I'd finished testing I unlinked it from the bridge and deleted the room in gitter. From that point onwards, the bridge didn't notice any message traffic inbound from gitter, displaying the same symptoms as seen above. Restarting the bridge made it work.

I don't know for sure if this is the same failure mode, but it's certainly *a* failure mode.

**Comment by leonerd** [comment]
It fell over again today at around 13:35. What's interesting is that this time (by looking at the metrics graphs) its file descriptor count appears to have dropped by 2. It did manage a steady 14 (with occasional spikes up at 15) while it was working. At the time that it stopped that count dropped to 12 (with spikes to 13). Running `lsof` on it this time didn't show the two `ESTABLISHED` sockets up to AWS; the only socket was the listening-mode one on :3551.

**Comment by leonerd** [comment]
FTR: hasn't happened again for a while.

**Comment by Half-Shot** [comment]
My assumption here is that @leonerd misclicked..
