### ISSUE TITLE
Alternatives for how to present edited messages: diff?

### ISSUE THREAD

**Issue by FireyFly** [matrix-org/matrix-appservice-gitter#7]
Currently, when a Gitter user edits a message the resulting message gets sent again to Matrix. This could generate some unnecessary noise when the edit is something minor (such as fixing a typo).

One alternative would be to provide a brief diff between the old and new message instead, which should work well for things such as a typo being fixed or a word being changed to a better synonym (which I imagine is the kind of things that edits would usually consist of?). Even better would be if colour could be used to denote inserted and removed characters. I'm thinking additions in green and deletions in red, with a few characters of context around changes. However, the colours might end up being more of a distraction instead so I guess it's a tradeoff.

**Comment by leonerd** [comment]
I don't think right now there's a standard set of rules for how to present colour formatting in Matrix messages. I agree it would be nice to present message edits a nicer way, but currently I don't know what that nicer way would look like.

I'll have a play with what can be done with diff, even if it's simple things like chopping off common prefix and suffix strings at least. As you say; most edits would be single typoes or single words

**Comment by leonerd** [comment]
An initial hack at this is now in 8795a59

**Comment by leonerd** [comment]
This has been running for a couple of months now - does it look good to you? If so I'd like to close the issue.

**Comment by FireyFly** [comment]
I searched logs a bit since I haven't been reading #neovim actively... looks good to me! Closing.
