### ISSUE TITLE
Gitter integration fails with mysterious 404

### ISSUE THREAD

**Issue by rcurtin** [matrix-org/matrix-appservice-gitter#85]
This is a follow-up of a conversation in the `Matrix Bridging` channel.

I have a Matrix channel `#mlpack:matrix.org` that I'd like to bridge to the related Gitter channel https://gitter.im/mlpack/mlpack.  The channel is created on Gitter like below:

![Screenshot 2019-11-04 at 10 35 09 AM](https://user-images.githubusercontent.com/1845039/68134621-64e75880-fef0-11e9-8051-9500a8c84afa.png)

That gives a working channel, shown in the left column of the following screenshot as `mlpack/mlpack`:

![Screenshot 2019-11-04 at 10 34 09 AM](https://user-images.githubusercontent.com/1845039/68134661-7466a180-fef0-11e9-93f9-b8359e076db4.png)

Then, I try to use the riot.im Gitter integration to connect to the room `mlpack/mlpack` but receive a 404:

![Screenshot 2019-11-04 at 10 36 26 AM](https://user-images.githubusercontent.com/1845039/68134713-82b4bd80-fef0-11e9-94dd-32d7ff837772.png)

However, if I try to bridge instead to the https://gitter.im/mlpack/mlpack.org room there is no problem.  I can try and provide more output but I don't really have too much in the way of debug output that I know how to get my hands on here.

Thanks!

**Comment by rcurtin** [comment]
Well, it seemed to work today.  So I will go ahead and close the issue.  However, I have no insight on whether a bug does exit or anything, so, feel free to reopen if it is worth keeping open. :)

**Comment by Half-Shot** [comment]
Nooo idea what is going, and I am going to causiously chalk it up as a Gitter oddity.
