### ISSUE TITLE
Crypto module could not be loaded - why?

### ISSUE THREAD

**Issue by IngwiePhoenix** [matrix-org/matrix-appservice-gitter#88]
Whenever I start the Gitter bridge, I see this:

```
$ forever logs 0
data:    index.js:8587 - Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
r```

And that is all the output I ever see. How can I fix that? Thanks! ^.^

**Comment by turt2live** [comment]
That's a normal error and nothing to worry about. Even if you did load the crypto module, e2e wouldn't work anyways.

**Comment by IngwiePhoenix** [comment]
I see, good to know!

Thank you. I am having other issues, such as the Gitterbot not showing up on my server in the room I told it to, but I will make separate issues. First im gonna try and see if I can solve this on my own.

By the way, some log output would be handy to have for this, as to be able to see if the service was able to connect and such.

**Comment by turt2live** [comment]
You'll probably want to h=join #bridges:matrix.org to troubleshoot rather than using the issue tracker for that
